[bug] Fix parsing of latest OLSR jsoninfo format
openwisp/netdiff pull request #96
Opened 2022-02-07 20:29 UTC by wnagele

OLSR jsoninfo plugin has changed the JSON output format in some of the "newer" releases. This adds support for parsing that - while remaining backward compatible.

2022-02-07 20:56 UTC, nemesisdesign requested changes
Hi @wnagele,

thank you for contributing!

Can you please provide a sample of the new format, so that we can update the automated tests?

2022-02-09 11:48 UTC, wnagele commented
I've ported the `links2` OLSR data into the new format and changed to run every testcase that has been using it to run for both the old and new format. This should give decent test coverage. Hope this is what you were after.

2022-02-20 07:31 UTC, wnagele commented
ping @nemesisdesign

2022-03-01 16:09 UTC, nemesisdesign reviewed
Thanks, we will test / review and do any improvements if needed asap.

2022-03-02 16:14 UTC, pandafy commented on tests/test_olsr.py
> +    return f'{testcase_func.__name__}_{param_num}_{format}'
I have added this to make the name of test case readable in verbose mode. Without this, the whole content of `param` was being appended to the test case name in verbose mode.

2022-03-02 18:07 UTC, nemesisdesign approved these changes

2022-03-02 18:08 UTC, merged

2022-03-02 18:08 UTC, nemesisdesign commented
Thanks @wnagele :+1: